# Generated by Django 2.0.5 on 2018-05-23 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blood_storage.BloodStorage')),
            ],
        ),
    ]
