# Generated by Django 2.0.5 on 2018-05-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodcollection',
            name='location_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bloodcollection',
            name='location_lon',
            field=models.FloatField(null=True),
        ),
    ]
