# Generated by Django 2.0.5 on 2018-05-23 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_user_days_past'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='days_past',
        ),
    ]
