# Generated by Django 2.0.5 on 2018-05-23 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location_lon', models.FloatField(null=True)),
                ('location_lat', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BloodStorageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('0-', '0-'), ('0+', '0+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3, null=True)),
                ('volume', models.FloatField(default=0.0)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_storage.BloodStorage')),
            ],
        ),
    ]
